# Generated by Django 2.1.3 on 2019-01-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images_paths', models.CharField(default='[]', max_length=50)),
                ('manufacture_date', models.CharField(max_length=50)),
                ('killometres', models.CharField(max_length=50)),
                ('owner_number', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('motorization', models.CharField(max_length=50)),
                ('performance_kw', models.CharField(max_length=50)),
                ('performance_hp', models.CharField(max_length=50)),
                ('add_date', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('repair', models.CharField(max_length=500)),
                ('defects', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
    ]
