# Generated by Django 2.1.4 on 2019-01-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190108_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='fuel',
            new_name='fuel_type',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='owner_number',
            new_name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='add_date',
            field=models.DateField(max_length=50),
        ),
    ]
